name: smartsocket
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  http:
  material_design_icons_flutter:
  latlng:
  flutter_map:
  geolocator:
  flutter_svg:
  pin_code_fields:
  linked_scroll_controller:
  intl:
  web_smooth_scroll:
  fl_chart:
  url_strategy:
  bouncing_widget: 
  get: ^5.0.0-beta.52
  carousel_slider:
  expansion_tile_card:
  dropdown_button2:
  loading_indicator: ^3.1.0

  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/svg/
    - assets/images/
    - assets/clientele_logos/

  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/Questrial-Regular.ttf
    - family: MontserratExtraBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
